pub mod bitops;
pub mod bloom;
pub mod cms;
pub mod cuckoo;
pub mod geos;
pub mod hashes;
pub mod hlls;
pub mod json;
pub mod keys;
pub mod lists;
pub mod server;
pub mod sets;
pub mod streams;
pub mod strings;
pub mod topk;
pub mod zsets;

use crate::commands::Command;

pub const ALL_COMMANDS: &[Command] = &[
    // strings
    strings::CMD_SET,
    strings::CMD_GET,
    strings::CMD_GETDEL,
    strings::CMD_GETSET,
    strings::CMD_SETNX,
    strings::CMD_SETEX,
    strings::CMD_PSETEX,
    strings::CMD_APPEND,
    strings::CMD_PREPEND,
    strings::CMD_STRLEN,
    strings::CMD_GETRANGE,
    strings::CMD_SUBSTR,
    strings::CMD_SETRANGE,
    strings::CMD_GETEX,
    strings::CMD_DIGEST,
    strings::CMD_GAT,
    strings::CMD_INCR,
    strings::CMD_INCRBY,
    strings::CMD_DECR,
    strings::CMD_DECRBY,
    strings::CMD_INCRBYFLOAT,
    strings::CMD_MSET,
    strings::CMD_MSETNX,
    strings::CMD_MGET,
    strings::CMD_CL_THROTTLE,
    // bitmaps
    bitops::CMD_BITCOUNT,
    bitops::CMD_BITPOS,
    bitops::CMD_BITFIELD,
    bitops::CMD_BITFIELD_RO,
    bitops::CMD_BITOP,
    bitops::CMD_GETBIT,
    bitops::CMD_SETBIT,
    // hyperloglog
    hlls::CMD_PFADD,
    hlls::CMD_PFCOUNT,
    hlls::CMD_PFMERGE,
    // bloom filters
    bloom::CMD_BF_RESERVE,
    bloom::CMD_BF_ADD,
    bloom::CMD_BF_MADD,
    bloom::CMD_BF_EXISTS,
    bloom::CMD_BF_MEXISTS,
    bloom::CMD_BF_INFO,
    bloom::CMD_BF_SCANDUMP,
    bloom::CMD_BF_LOADCHUNK,
    // count-min sketches
    cms::CMD_CMS_INITBYDIM,
    cms::CMD_CMS_INITBYPROB,
    cms::CMD_CMS_INCRBY,
    cms::CMD_CMS_QUERY,
    cms::CMD_CMS_INFO,
    cms::CMD_CMS_MERGE,
    // cuckoo filters
    cuckoo::CMD_CF_RESERVE,
    cuckoo::CMD_CF_ADD,
    cuckoo::CMD_CF_ADDNX,
    cuckoo::CMD_CF_EXISTS,
    cuckoo::CMD_CF_MEXISTS,
    cuckoo::CMD_CF_INFO,
    cuckoo::CMD_CF_COUNT,
    cuckoo::CMD_CF_DEL,
    cuckoo::CMD_CF_INSERT,
    cuckoo::CMD_CF_INSERTNX,
    cuckoo::CMD_CF_COMPACT,
    // topk
    topk::CMD_TOPK_RESERVE,
    topk::CMD_TOPK_ADD,
    topk::CMD_TOPK_INCRBY,
    topk::CMD_TOPK_QUERY,
    topk::CMD_TOPK_COUNT,
    topk::CMD_TOPK_LIST,
    topk::CMD_TOPK_INFO,
    // keys
    keys::CMD_DEL,
    keys::CMD_EXISTS,
    keys::CMD_DELEX,
    keys::CMD_EXPIRE,
    keys::CMD_PEXPIRE,
    keys::CMD_EXPIREAT,
    keys::CMD_PEXPIREAT,
    keys::CMD_TTL,
    keys::CMD_PTTL,
    keys::CMD_PERSIST,
    keys::CMD_TYPE,
    keys::CMD_KEYS,
    keys::CMD_TOUCH,
    keys::CMD_UNLINK,
    keys::CMD_STICK,
    keys::CMD_MOVE,
    keys::CMD_RENAME,
    keys::CMD_RENAMENX,
    keys::CMD_COPY,
    keys::CMD_RANDOMKEY,
    keys::CMD_EXPIRETIME,
    keys::CMD_PEXPIRETIME,
    keys::CMD_SCAN,
    keys::CMD_RM,
    keys::CMD_SORT,
    keys::CMD_SORT_RO,
    keys::CMD_FIELDEXPIRE,
    keys::CMD_FIELDTTL,
    keys::CMD_DUMP,
    keys::CMD_RESTORE,
    // lists
    lists::CMD_LPUSH,
    lists::CMD_RPUSH,
    lists::CMD_LPUSHX,
    lists::CMD_RPUSHX,
    lists::CMD_LPOP,
    lists::CMD_RPOP,
    lists::CMD_LLEN,
    lists::CMD_LRANGE,
    lists::CMD_LINDEX,
    lists::CMD_LSET,
    lists::CMD_LREM,
    lists::CMD_LTRIM,
    lists::CMD_LPOS,
    lists::CMD_LINSERT,
    lists::CMD_LMOVE,
    lists::CMD_RPOPLPUSH,
    lists::CMD_LMPOP,
    lists::CMD_BLPOP,
    lists::CMD_BRPOP,
    lists::CMD_BLMOVE,
    lists::CMD_BRPOPLPUSH,
    lists::CMD_BLMPOP,
    // hashes
    hashes::CMD_HSET,
    hashes::CMD_HMSET,
    hashes::CMD_HGET,
    hashes::CMD_HMGET,
    hashes::CMD_HDEL,
    hashes::CMD_HLEN,
    hashes::CMD_HGETALL,
    hashes::CMD_HKEYS,
    hashes::CMD_HVALS,
    hashes::CMD_HEXISTS,
    hashes::CMD_HINCRBY,
    hashes::CMD_HINCRBYFLOAT,
    hashes::CMD_HSTRLEN,
    hashes::CMD_HSETNX,
    hashes::CMD_HSETEX,
    hashes::CMD_HEXPIRE,
    hashes::CMD_HTTL,
    hashes::CMD_HPEXPIRETIME,
    hashes::CMD_HGETEX,
    hashes::CMD_HRANDFIELD,
    hashes::CMD_HSCAN,
    // sets
    sets::CMD_SADD,
    sets::CMD_SADDEX,
    sets::CMD_SREM,
    sets::CMD_SMEMBERS,
    sets::CMD_SISMEMBER,
    sets::CMD_SMISMEMBER,
    sets::CMD_SCARD,
    sets::CMD_SPOP,
    sets::CMD_SRANDMEMBER,
    sets::CMD_SSCAN,
    sets::CMD_SINTER,
    sets::CMD_SUNION,
    sets::CMD_SDIFF,
    sets::CMD_SINTERSTORE,
    sets::CMD_SUNIONSTORE,
    sets::CMD_SDIFFSTORE,
    sets::CMD_SINTERCARD,
    sets::CMD_SMOVE,
    // zsets
    zsets::CMD_ZADD,
    zsets::CMD_ZREM,
    zsets::CMD_ZSCORE,
    zsets::CMD_ZMSCORE,
    zsets::CMD_ZCARD,
    zsets::CMD_ZINCRBY,
    zsets::CMD_ZRANK,
    zsets::CMD_ZREVRANK,
    zsets::CMD_ZRANGE,
    zsets::CMD_ZRANGESTORE,
    zsets::CMD_ZINTERCARD,
    zsets::CMD_ZUNION,
    zsets::CMD_ZUNIONSTORE,
    zsets::CMD_ZINTER,
    zsets::CMD_ZINTERSTORE,
    zsets::CMD_ZDIFF,
    zsets::CMD_ZDIFFSTORE,
    zsets::CMD_ZRANGEBYSCORE,
    zsets::CMD_ZREVRANGEBYSCORE,
    zsets::CMD_ZCOUNT,
    zsets::CMD_ZREMRANGEBYRANK,
    zsets::CMD_ZREMRANGEBYSCORE,
    zsets::CMD_ZPOPMIN,
    zsets::CMD_ZPOPMAX,
    zsets::CMD_ZMPOP,
    zsets::CMD_BZMPOP,
    zsets::CMD_BZPOPMIN,
    zsets::CMD_BZPOPMAX,
    zsets::CMD_ZRANGEBYLEX,
    zsets::CMD_ZREVRANGEBYLEX,
    zsets::CMD_ZREVRANGE,
    zsets::CMD_ZLEXCOUNT,
    zsets::CMD_ZREMRANGEBYLEX,
    zsets::CMD_ZRANDMEMBER,
    zsets::CMD_ZSCAN,
    // geos
    geos::CMD_GEOADD,
    geos::CMD_GEODIST,
    geos::CMD_GEOHASH,
    geos::CMD_GEOPOS,
    geos::CMD_GEOSEARCH,
    geos::CMD_GEOSEARCHSTORE,
    geos::CMD_GEORADIUS,
    geos::CMD_GEORADIUS_RO,
    geos::CMD_GEORADIUSBYMEMBER,
    geos::CMD_GEORADIUSBYMEMBER_RO,
    // json
    json::CMD_JSON_GET,
    json::CMD_JSON_MGET,
    json::CMD_JSON_TYPE,
    json::CMD_JSON_STRLEN,
    json::CMD_JSON_OBJLEN,
    json::CMD_JSON_ARRLEN,
    json::CMD_JSON_TOGGLE,
    json::CMD_JSON_NUMINCRBY,
    json::CMD_JSON_NUMMULTBY,
    json::CMD_JSON_DEL,
    json::CMD_JSON_FORGET,
    json::CMD_JSON_OBJKEYS,
    json::CMD_JSON_STRAPPEND,
    json::CMD_JSON_CLEAR,
    json::CMD_JSON_ARRPOP,
    json::CMD_JSON_ARRTRIM,
    json::CMD_JSON_ARRINSERT,
    json::CMD_JSON_ARRAPPEND,
    json::CMD_JSON_ARRINDEX,
    json::CMD_JSON_DEBUG,
    json::CMD_JSON_RESP,
    json::CMD_JSON_SET,
    json::CMD_JSON_MSET,
    json::CMD_JSON_MERGE,
    // streams
    streams::CMD_XADD,
    streams::CMD_XLEN,
    streams::CMD_XRANGE,
    streams::CMD_XREVRANGE,
    streams::CMD_XDEL,
    streams::CMD_XTRIM,
    streams::CMD_XREAD,
    streams::CMD_XGROUP,
    streams::CMD_XREADGROUP,
    streams::CMD_XACK,
    streams::CMD_XPENDING,
    streams::CMD_XINFO,
    streams::CMD_XSETID,
    streams::CMD_XCLAIM,
    streams::CMD_XAUTOCLAIM,
    // server / connection
    server::CMD_PING,
    server::CMD_ECHO,
    server::CMD_SELECT,
    server::CMD_AUTH,
    server::CMD_COMMAND,
    server::CMD_HELLO,
    server::CMD_INFO,
    server::CMD_CONFIG,
    server::CMD_CLIENT,
    server::CMD_DBSIZE,
    server::CMD_FLUSHDB,
    server::CMD_FLUSHALL,
    server::CMD_TIME,
    server::CMD_MULTI,
    server::CMD_EXEC,
    server::CMD_DISCARD,
    server::CMD_RESET,
    server::CMD_WATCH,
    server::CMD_UNWATCH,
    server::CMD_ROLE,
    server::CMD_LASTSAVE,
    server::CMD_LATENCY,
    server::CMD_SLOWLOG,
    server::CMD_MEMORY,
    server::CMD_DEBUG,
    server::CMD_SAVE,
    server::CMD_BGSAVE,
    server::CMD_PUBLISH,
    server::CMD_SUBSCRIBE,
    server::CMD_UNSUBSCRIBE,
    server::CMD_PSUBSCRIBE,
    server::CMD_PUNSUBSCRIBE,
    server::CMD_PUBSUB,
    server::CMD_SPUBLISH,
    server::CMD_SSUBSCRIBE,
    server::CMD_SUNSUBSCRIBE,
    server::CMD_QUIT,
    server::CMD_MONITOR,
    server::CMD_SHUTDOWN,
    server::CMD_WAIT,
    server::CMD_REPLCONF,
    server::CMD_REPLICAOF,
    server::CMD_SLAVEOF,
    server::CMD_ADDREPLICAOF,
    server::CMD_REPLTAKEOVER,
    server::CMD_MODULE,
    server::CMD_FUNCTION,
    server::CMD_SCRIPT,
    server::CMD_SHRINK,
    server::CMD_EVAL,
    server::CMD_EVALSHA,
    server::CMD_DFLY,
];
