pub mod bitops;
pub mod geos;
pub mod hashes;
pub mod hlls;
pub mod keys;
pub mod lists;
pub mod server;
pub mod sets;
pub mod streams;
pub mod strings;
pub mod zsets;

use crate::commands::Command;

pub const ALL_COMMANDS: &[Command] = &[
    // strings
    strings::CMD_SET,
    strings::CMD_GET,
    strings::CMD_GETDEL,
    strings::CMD_GETSET,
    strings::CMD_SETNX,
    strings::CMD_SETEX,
    strings::CMD_PSETEX,
    strings::CMD_APPEND,
    strings::CMD_PREPEND,
    strings::CMD_STRLEN,
    strings::CMD_GETRANGE,
    strings::CMD_SUBSTR,
    strings::CMD_SETRANGE,
    strings::CMD_GETEX,
    strings::CMD_DIGEST,
    strings::CMD_GAT,
    strings::CMD_INCR,
    strings::CMD_INCRBY,
    strings::CMD_DECR,
    strings::CMD_DECRBY,
    strings::CMD_INCRBYFLOAT,
    strings::CMD_MSET,
    strings::CMD_MSETNX,
    strings::CMD_MGET,
    strings::CMD_CL_THROTTLE,
    // bitmaps
    bitops::CMD_BITCOUNT,
    bitops::CMD_BITPOS,
    bitops::CMD_BITFIELD,
    bitops::CMD_BITFIELD_RO,
    bitops::CMD_BITOP,
    bitops::CMD_GETBIT,
    bitops::CMD_SETBIT,
    // hyperloglog
    hlls::CMD_PFADD,
    hlls::CMD_PFCOUNT,
    hlls::CMD_PFMERGE,
    // keys
    keys::CMD_DEL,
    keys::CMD_EXISTS,
    keys::CMD_DELEX,
    keys::CMD_EXPIRE,
    keys::CMD_PEXPIRE,
    keys::CMD_EXPIREAT,
    keys::CMD_PEXPIREAT,
    keys::CMD_TTL,
    keys::CMD_PTTL,
    keys::CMD_PERSIST,
    keys::CMD_TYPE,
    keys::CMD_KEYS,
    keys::CMD_TOUCH,
    keys::CMD_UNLINK,
    keys::CMD_STICK,
    keys::CMD_MOVE,
    keys::CMD_RENAME,
    keys::CMD_RENAMENX,
    keys::CMD_COPY,
    keys::CMD_RANDOMKEY,
    keys::CMD_EXPIRETIME,
    keys::CMD_PEXPIRETIME,
    keys::CMD_SCAN,
    keys::CMD_SORT,
    keys::CMD_SORT_RO,
    keys::CMD_FIELDEXPIRE,
    keys::CMD_FIELDTTL,
    keys::CMD_DUMP,
    keys::CMD_RESTORE,
    // lists
    lists::CMD_LPUSH,
    lists::CMD_RPUSH,
    lists::CMD_LPUSHX,
    lists::CMD_RPUSHX,
    lists::CMD_LPOP,
    lists::CMD_RPOP,
    lists::CMD_LLEN,
    lists::CMD_LRANGE,
    lists::CMD_LINDEX,
    lists::CMD_LSET,
    lists::CMD_LREM,
    lists::CMD_LTRIM,
    lists::CMD_LPOS,
    // hashes
    hashes::CMD_HSET,
    hashes::CMD_HMSET,
    hashes::CMD_HGET,
    hashes::CMD_HMGET,
    hashes::CMD_HDEL,
    hashes::CMD_HLEN,
    hashes::CMD_HGETALL,
    hashes::CMD_HKEYS,
    hashes::CMD_HVALS,
    hashes::CMD_HEXISTS,
    hashes::CMD_HINCRBY,
    hashes::CMD_HINCRBYFLOAT,
    hashes::CMD_HSTRLEN,
    hashes::CMD_HSETNX,
    hashes::CMD_HSETEX,
    hashes::CMD_HEXPIRE,
    hashes::CMD_HTTL,
    hashes::CMD_HPEXPIRETIME,
    hashes::CMD_HGETEX,
    hashes::CMD_HRANDFIELD,
    hashes::CMD_HSCAN,
    // sets
    sets::CMD_SADD,
    sets::CMD_SADDEX,
    sets::CMD_SREM,
    sets::CMD_SMEMBERS,
    sets::CMD_SISMEMBER,
    sets::CMD_SMISMEMBER,
    sets::CMD_SCARD,
    sets::CMD_SPOP,
    sets::CMD_SRANDMEMBER,
    sets::CMD_SSCAN,
    sets::CMD_SINTER,
    sets::CMD_SUNION,
    sets::CMD_SDIFF,
    sets::CMD_SINTERSTORE,
    sets::CMD_SUNIONSTORE,
    sets::CMD_SDIFFSTORE,
    sets::CMD_SINTERCARD,
    sets::CMD_SMOVE,
    // zsets
    zsets::CMD_ZADD,
    zsets::CMD_ZREM,
    zsets::CMD_ZSCORE,
    zsets::CMD_ZMSCORE,
    zsets::CMD_ZCARD,
    zsets::CMD_ZINCRBY,
    zsets::CMD_ZRANK,
    zsets::CMD_ZREVRANK,
    zsets::CMD_ZRANGE,
    zsets::CMD_ZRANGEBYSCORE,
    zsets::CMD_ZREVRANGEBYSCORE,
    zsets::CMD_ZCOUNT,
    zsets::CMD_ZREMRANGEBYRANK,
    zsets::CMD_ZREMRANGEBYSCORE,
    zsets::CMD_ZPOPMIN,
    zsets::CMD_ZPOPMAX,
    zsets::CMD_ZRANGEBYLEX,
    // geos
    geos::CMD_GEOADD,
    geos::CMD_GEODIST,
    geos::CMD_GEOHASH,
    geos::CMD_GEOPOS,
    geos::CMD_GEOSEARCH,
    geos::CMD_GEOSEARCHSTORE,
    geos::CMD_GEORADIUS,
    geos::CMD_GEORADIUS_RO,
    geos::CMD_GEORADIUSBYMEMBER,
    geos::CMD_GEORADIUSBYMEMBER_RO,
    // streams
    streams::CMD_XADD,
    streams::CMD_XLEN,
    streams::CMD_XRANGE,
    streams::CMD_XREVRANGE,
    streams::CMD_XDEL,
    streams::CMD_XTRIM,
    streams::CMD_XREAD,
    streams::CMD_XGROUP,
    streams::CMD_XREADGROUP,
    streams::CMD_XACK,
    streams::CMD_XPENDING,
    streams::CMD_XINFO,
    streams::CMD_XSETID,
    streams::CMD_XCLAIM,
    streams::CMD_XAUTOCLAIM,
    // server / connection
    server::CMD_PING,
    server::CMD_ECHO,
    server::CMD_SELECT,
    server::CMD_AUTH,
    server::CMD_COMMAND,
    server::CMD_HELLO,
    server::CMD_INFO,
    server::CMD_CONFIG,
    server::CMD_CLIENT,
    server::CMD_DBSIZE,
    server::CMD_FLUSHDB,
    server::CMD_FLUSHALL,
    server::CMD_TIME,
];
